<?php
/*
 * rbook Recipe Management System
 * Copyright (C) 2005 Andrew Violette andrew@andrewviolette.net
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

/**
 * Resource bundle for Estonian language.
 *
 * @author Mark Leiner/Henrik Pihl
 * @since 1.3.0.1
 * @version $Id: resources_et.php,v 1.1 2006/12/21 07:55:48 ahven Exp $
 */

$i18n_messages_et = 
    array('importTitle' => "Impordi",
        "active" => "aktiivne",
        "invited" => "kutse saadetud",
        "disabled" => "passiivne",
        'Profile' => 'Profiil',
        'addUser' => 'Lisa Kasutaja',
        'editUser' => 'Muuda Kasutajat',
        'VerifyInvitation' => 'T&otilde;esta kutsumist',
        'userOrPasswordIncorrect' => 'Kasutaja nimi v&otilde;i parool on vale.',
        "userCannotBeDeleted" => "M&otilde;ningaid kasutajaid ei saanud kustutada; t&otilde;en&auml;oline p&otilde;hjus on see, et nad omavad retsepte.  Kas kustuta nende kasutajate retseptid v&otilde;i muuda mitteaktiivseks nende kontod.",
        'accountDisabled' => 'See konto pole aktiivne.',
        'noRecipeSelected' => "Retsepti pole valitud.",
        "initialPassword" => "Kasutaja algne parool on <em>password</em>.",
        "resetPasswordDesc" => "Muuda kasutaja parool tagasi <em>password</em>:",
        "resetPassword" => "Reseti parool",
        'editCategories' => "Muuda kategooriaid",
        "newCategory" => "Uus kategooria",
        "selectFileToImport" => "Vali fail importimiseks:",
        "importWarning" => "Hoiatus! Impordifail kustutab &auml;ra k&otilde;ik seaded ja asendab kasutaja, kategooria, ja retseptidega, mis on antud failis defineeritud.",
        "File" => "Fail",
        "Created" => "Loodud",
        "delete" => "kustuta",
        "noImportFiles" => "Impordikataloogis pole faile.",
        "DeleteQuestion" => "Kustutan?",
        "categoryName" => "Nimi",
        "categoryNew" => "Uus",
        "Delete" => "Kustuta",
        "Go" => "Mine",
        'remove' => 'eemalda',
        "TitleSearch" => "Pealkirja otsing",
        "newRecipe" => "uus retsept",
        'MyRecipes' => 'Minu retseptid',
        "myRecipes" => "minu retseptid",
        "conversion" => "teisendamine",
        "exportMsg" => "M&auml;&auml;ra ekspordifailile nimi.  See saab pandud kataloogi, mis on m&auml;&auml;ratud konfiguratsioonifailis.",
        "Type" => "T&uuml;&uuml;p",
        "Status" => "Staatus",
        "admin" => "administraator",
        "readonly" => "ainult lugemiseks",
        "normal" => "normaalne",
        "home" => "avaleht",
        "Step" => "Samm",
        "OldPassword" => "Vana parool:",
        "NewPassword" => "Uus parool:",
        "ConfirmNewPassword" => "Korda uut parooli:",
        "Ingredients" => "Koostisained",
        "Amount" => "Kogus",
        "Description" => "kirjeldus",
        "upButton" => "&uuml;les",
        "downButton" => "alla",
        "AddIngredient" => "lisa",
        "Conversions" => "Teisendamised",
        "Grams" => "Grammid",
        "Milligrams" => "Milligrammid",
        "Ounces" => "Untsid",
        "Pounds" => "Naelad",
        "IngredientSets" => "Koostisained",
        "AddIngredientSet" => "Lisa koostisosa",
        "PickReplacementCategory" => "Vali asendamise kategooria",
        "replacementMsg" => "Selles kategoorias, mida te tahate kustutada on retsepte.  Selektige kategooria allolevast listist, mis asendavad kategooriaid, mida te kustutate.",
        'User' => 'Kasutaja',
        'Steps' => 'valmistamine',
        'Note' => 'M&auml;rge',
        'ExportFile' => "V&auml;ljasta faili:",
        'submittedBy' => 'Lisanud:',
        'rightsLevel' => '&Otilde;iguste Tase',
        'recipecount' => 'Retseptid',
        'logout' => 'V&auml;ljalogimine',
        'Login' => 'Sisselogimine',
        'Email' => 'E-mail:',
        'Name' => 'Nimi:',
        'Submit' => 'Kinnita',
        'Password' => 'Parool:',
        'rememberme' => 'M&auml;leta mind',
        'invite' => 'kutsu',
        'Invite' => 'Kutsu',
        'Invitations' => 'Kutsed',
        'remainingInvitations' => 'J&auml;rgij&auml;&auml;nud kutseid',
        'Admin' => 'Administraator',
        'Users' => 'Kasutajad',
        'Import' => 'Sisesta',
        'Export' => 'V&auml;ljasta',
        'Categories' => 'Kategooriad',
        'About' => 'Info',
        'deleteRecipe' => 'kustuta retsept',
        'Information' => 'Informatsioon',
        'Source' => 'Allikas',
        'Preheat' => 'Eelt&ouml;&ouml;d',
        'Title' => 'Pealkiri',
        'Category' => 'Kategooria',
        'Readonly' => 'Ainult lugemiseks',
        'Normal' => 'Normaalne',
        'Admin' => 'Administraator',
        'Passwords' => 'Paroolid',
        'Save' => 'Salvesta',
        'Cancel' => 'T&uuml;hista',
        'Continue' => 'J&auml;tka',
        'disabled' => 'blokeeritud',
        'addToMyRecipes' => 'lisa minu retseptidesse',
        'editRecipe' => 'muuda retsepti',
        'leaveBlank' => 'J&auml;ta need v&auml;ljad t&uuml;hjaks kui sa ei taha muuta oma parooli',
        'readonlyDesc' => 'Saab otsida, sirvida ja vaadata retsepte',
        'normalDesc' => 'Saab otsida, sirvida, vaadata ja muuta retsepte, mis on loodud enda poolt.  Saab kutsuda teisi liikmeks.',
        'adminDesc' => 'Saab otsida, sirvida, vaadata, ja muuta k&otilde;iki retsepte.  Saab luua ja muuta kasutajaid ja kategooriaid.',
        'noActiveRecipe' => 'Pole aktiivseid retsepte.',
        'invalidInvitation' => 'Vale kutse',
        'invitationUsed' => 'Kutset on juba kasutatud',
        'emailDoesNotMatch' => 'E-mail ei sobi kutsega',
        'mostRecentAdditions' => 'Viimased lisamised',
        'errorRetrievingUser' => 'Eba&otilde;nnestunud taastamine kasutajale: %s',
        'noExportFileSpecified' => "V&auml;ljastusfaili pole m&auml;&auml;ratud.",
        'exportSuccessful' => 'Eksportimine &otilde;nnestus!',
        'forgotPassword' => 'Unustasin parooli',
        'noPermissionToEditRecipe' => "Sul ei ole &otilde;igust muuta seda retsepti.",
        'noPermissionToDeleteRecipe' => 'Sul ei ole &otilde;igust kustutada seda retsepti.',
        'activationLinkSent' => 'E-mail on saadetud su aadressile koos lingiga, mis taastab sinu konto.',
        'recoverPassword' => 'Taasta parool',
        'emailToRecover' => 'Palun sisestage e-maili aadress, mida kasutati konto loomisel.  E-mail saadetakse sellele aadressile edasiste instruktsioonidega',
        'userNotInSystem' => 'Kasutajat ei ole s&uuml;steemis.',
        'emailUnsuccessful' => 'E-maili saatmisel tekkis probleem.  V&otilde;imalikud p&otilde;hjused sisaldavad: e-maili server oli maas, e-mail on eba&otilde;igesti seadistatud v&otilde;i eba&otilde;ige e-mailiaadress.',
        'invalidAction' => 'Eba&otilde;ige tegutsemine.',
        'sendInvitation' => 'Saada kutse',
        'invitationSuccessful' => "Kutse edukalt saadetud.",
        'personalMessage' => 'Teade:',
        'invitationSubject' => 'Kutse kasutajale %s',
        'userinsystem' => "Kasutaja on juba s&uuml;steemis.",
        "areYouSure" => "Oled sa kindel?",
        "no" => "ei",
        "yes" => "jah",
        "VolumetricConversions" => "Mahu teisendamised",
        "Measurement" => "M&otilde;&otilde;te&uuml;hik",
        "Value" => "V&auml;&auml;rtus",
        "Teaspoons" => "Teelusikad",
        "Tablespoons" => "Supilusikad",
        "FluidOunces" => "Vedelik untsid",
        "Cups" => "Tassid",
        "Pints" => "Pindid",
        "Quarts" => "Kvardid",
        "Gallons" => "Gallonid",
        "Liters" => "Liitrid",
	"Serves" => "Portsjonite hulk",
        "ExportResults" => "V&auml;ljastamise tulemused",
        "ExportImport" => "V&auml;ljastamine/Sisestamine",
        "MassConversions" => "Massi teisendamised",
        "cantDeleteYourself" => "Sa ei saa ennast kustutada!",
        "invitationsNotEnabled" => "Kutsed ei ole aktiivsed.  Kliki  <a href=\"http://rbook.andrewviolette.net/documentation/admin/invitations/\">Siia</a> instruktsioonideks, kuidas kutsed aktiveerida. (ainult lehe administraatorid n&auml;evad seda teksti)",
        "commaSeparated" => "(komaga eraldatud)",
        "addPictureCaption" => "Pealkiri",
        "addPicturePathToImage" => "Tee pildini",
        "addPictureAddPicture" => "Lisa pilt",
        "sortIngredientsHelp" => "Et muuta asetust, vali kustahes peale sisestuskasti, Siis tiri ja lase lahti koostisaine uude kohta",
        "sortStepsHelp" => "Et muuta asetust, vali kustahes peale sisestuskasti, siis tiri ja lase lahti aste uude kohta",
	"addPicture" => "lisa pilt",
	"deletePicture" => "eemalda pilt",
	"addPictureTo" => "Lisa pilt retseptile ",
	"searchResults1" => "Leiti",
	"searchResults2" => "vastet",
	"thumbnail" => "pisipilt",
	"noThumbnail" => "pisipilti pole",
	"noImage" => "images/noimage.gif",
	"NewUser" => "Uus kasutaja",
	"DeleteSelected" => "Kustuta valitud",
	"UProfile" => "profiil",
	"searchGo" => "Otsi",
	"recipesBy" => "Retseptid autorite j&auml;rgi: ",
	"verifyEmail" => "Korda e-maili:",
	"ImpExpDisabled" => "Et importida/eksportida andmeid, tuleks config.php-s defineerida IMPORTDIR",
	"submittedCat" => "Kategooria:",
	"result_set_Results" => "Tulemused",
	"submittedOn" => "Millal:",
	"NewTitle" => "Uus pealkiri",
	"AddStep" => "Uus samm",
        "invalidImgType" => "Vale fail: Ainult gif ja jpg on toetatud hetkel.",
        "notAdminExport" => "Sa pead olema administraator, et saaksid eksporte alla laadida!",
        "noImportDir" => "Süsteem ei ole seadistatud impordi- ja ekspordiks.",
        "noImportFile" => "Impordifaili ei ole ette näidatud",
        "errorOpenImport" => "Ei suutnud avada faili: ",
        "passwordChanged" => "Parool edukalt vahetatud.",
        "numORecipes" => "Retseptide arv:",
        "numOCategories" => "Kategooriate arv:",
        "numOUsers" => "Kasutajate arv:"
        );
?>
