<?php
/*
 * rbook Recipe Management System
 * Copyright (C) 2005 Andrew Violette andrew@andrewviolette.net
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

/**
 * Resource bundle for German language.
 *
 * @author Maschine
 * @since 1.4
 * @version $Id: resources_de.php,v 1.7 2007/04/10 21:42:33 maschine Exp $
 */

$i18n_messages_de = 
array(
'accountDisabled' => 'Dieser Account ist deaktiviert.',
"active" => "aktiv",
'addUser' => 'Nutzer hinzufügen',
"Bookmark" => "Als Lesezeichen speichern",
"Created" => "Erstellt",
"delete" => "löschen",
"DeleteQuestion" => "Wirklich Löschen?",
"DiscardAndView" => "Änderungen verwerfen",
"disabled" => "deaktiviert",
'editCategories' => "Kategorien bearbeiten",
'editUser' => 'Nutzer bearbeiten',
'EditGroceryList' => 'Bearbeiten',
"File" => "Datei",
"SortBy" => "Sortieren nach: {0} / {1}",
"popular" => "Beliebteste Rezepte",
"recent" => "Neueste Rezepte",
"ProfileHeader" => "Profil: {0}",
"SeeAll" => "Zeige alle {0} Rezepte von {1}",
"Favorite" => "Lieblingsessen",
"Website" => "Website",
"deleteIngredientSetTooltip" => "Den ganzen Zutatensatz löschen",
"MostRecentRecipesBy" => "Neueste Rezepte von {0}",
"MemberSince" => "Mitglied seit: {0}",
'importTitle' => "Import",
"importWarning" => "Achtung!!! Das Importieren einer Datei wird alle vorhandenen Rezepte, Kategorien und Nutzer überschreiben.",
"initialPassword" => "Das anfängliche Passwort des Nutzers ist <em>password</em>.",
"invited" => "eingeladen",
"newCategory" => "Neue Kategorie",
"noImportFiles" => "Keine Importdateien in der Ablagezone.",
'noRecipeSelected' => "Kein Rezept ausgewählt.",
'Profile' => 'Profil',
"resetPassword" => "Passwort zurücksetzen",
"resetPasswordDesc" => "Das Passwort dieses Nutzers wieder zu <em>password</em> ändern:",
"SaveAndView" => "Speichern und Ansehen",
"saveToDelicious" => "Speichern bei del.icio.us",
"saveToGoogleBookmarks" => "Speichern bei Google",
"selectFileToImport" => "Bitte eine Datei zum Importieren auswählen:",
"userCannotBeDeleted" => "Einige Nutzer konnten nicht gelöscht werden; wahrscheinlich, weil sie noch Rezepte besitzen.  Entweder diese Rezepte löschen, oder den Account des Nutzers einfach deaktivieren.",
'userOrPasswordIncorrect' => 'Falscher Benutzername oder falsches Passwort.',
'VerifyInvitation' => 'Einladung Überprüfen',
"categoryName" => "Name",
"categoryNew" => "Neu",
"Delete" => "Löschen",
"Go" => "Los!",
'remove' => 'entfernen',
"TitleSearch" => "Suche nach Titel",
"newRecipe" => "Neues Rezept",
'MyRecipes' => 'Meine Rezepte',
"myRecipes" => "Meine Rezepte",
"conversion" => "Umrechnung",
"exportMsg" => "Bitte einen Dateinamen für die Exportdatei eingeben. Die Datei wird dann in dem Verzeichnis abgelegt, das dafür in der Konfiguration angegeben wurde.",
"Type" => "Typ",
"Status" => "Status",
"admin" => "Administator",
"readonly" => "nur lesen",
"normal" => "normal",
"home" => "Startseite",
"Step" => "Schritt",
"OldPassword" => "Altes Passwort",
"NewPassword" => "Neues Passwort",
"ConfirmNewPassword" => "Neues Passwort bestätigen",
"Ingredients" => "Zutaten",
"Amount" => "Menge",
"Description" => "Beschreibung",
"upButton" => "nach Oben",
"downButton" => "nach Unten",
"AddIngredient" => "hinzufügen",
"Conversions" => "Umrechnungen",
"Grams" => "Gramm",
"Milligrams" => "Milligramm",
"Ounces" => "Unzen (USA)",
"Pounds" => "Pfund (USA)",
"IngredientSets" => "Zutaten",
"AddIngredientSet" => "Neuen Zutatensatz hinzufügen",
"PickReplacementCategory" => "Eine Kategorie zum Ersetzen auswählen",
"replacementMsg" => "In dieser Kategorie befinden sich noch Rezepte. Bitte wähle eine Kategorie, die anstelle der zu löschenden Kategorie benutzt werden soll.",
'User' => 'Nutzer',
'Steps' => 'Schritte',
'Note' => 'Hinweis',
'Notes' => 'Hinweise',
'ExportFile' => "Exportdatei:",
'submittedBy' => 'Hinzugefügt von:',
'rightsLevel' => 'Rechte für den neuen Nutzer',
'recipecount' => 'Rezepte',
'logout' => 'Logout',
'Login' => 'Login',
'UserName' => 'Benutzername',
'Email' => 'E-Mail',
'Name' => 'Name',
'Submit' => 'Abschicken',
'Password' => 'Passwort',
'rememberme' => 'Login speichern',
'invite' => 'einladen',
'Invite' => 'einladen',
'Invitations' => 'Einladungen',
'remainingInvitations' => 'Verbleibende Einladungen',
'Admin' => 'Administrator',
'Users' => 'Nutzer',
'Import' => 'Import',
'Export' => 'Export',
'Categories' => 'Kategorien',
'About' => '&Uuml;ber rbook',
'deleteRecipe' => 'Rezept löschen',
'printRecipe' => 'Rezept drucken',
'Information' => 'Information',
'Source' => 'Quelle',
'Preheat' => 'Vorheizen',
'Title' => 'Titel',
'Category' => 'Kategorie',
'Readonly' => 'Nur lesen',
'Normal' => 'Normal',
'Admin' => 'Administrator',
'Passwords' => 'Passwörter',
'Save' => 'Speichern',
'Cancel' => 'Abbrechen',
'Continue' => 'Weiter',
'disabled' => 'deaktivieren',
'addToMyRecipes' => 'Zu meinen Rezepten hinzufügen',
'editRecipe' => 'Rezept bearbeiten',
'leaveBlank' => 'Bitte diese Felder freilassen, wenn du dein Passwort nicht ändern möchtest.',
'readonlyDesc' => 'Kann alle Rezepte durchsuchen und ansehen.',
'normalDesc' => 'Kann alle Rezepte durchsuchen und ansehen, außerdem die von ihm erstellten Rezepte bearbeiten. Kann Einladungen an neue Mitglieder verschicken.',
'adminDesc' => 'Kann alle Rezepte durchsuchen, ansehen und bearbeiten. Kann Nutzer und Kategorien anlegen und bearbeiten.',
'noActiveRecipe' => 'Kein aktives Rezept.',
'invalidInvitation' => 'Ungültiger Einladungscode.',
'invitationUsed' => 'Einladungscode wurde bereits benutzt.',
'emailDoesNotMatch' => 'E-Mail stimmt nicht mit der aus der Einladung überein.',
'mostRecentAdditions' => 'Neueste Rezepte',
'errorRetrievingUser' => 'Fehler beim Finden des folgenden Nutzers: %s',
'noExportFileSpecified' => "Keine Exportdatei angegeben.",
'exportSuccessful' => 'Export erfolgreich!',
'forgotPassword' => 'Passwort vergessen',
'noPermissionToEditRecipe' => "Sorry, du darfst dieses Rezept nicht bearbeiten.",
'noPermissionToDeleteRecipe' => 'Sorry, du darfst dieses Rezept nicht löschen.',
'activationLinkSent' => 'Eine E-Mail wurde an deine angegebene Adresse verschickt. Mit dem darin enthaltenen Link kannst du deinen Account wieder aktivieren.',
'recoverPassword' => 'Passwort wiederherstellen',
'emailToRecover' => 'Bitte gib die E-Mail-Adresse ein, die du zum Erstellen dieses Accounts genutzt hast. Eine Mail mit weiteren Anweisungen wird an diese Adresse verschickt.',
'userNotInSystem' => 'Nutzer konnte nicht gefunden werden.',
'emailUnsuccessful' => 'Es gab ein Problem beim verschicken der Mail. Mögliche Gründe: Mailserver falsch bzw. noch gar nicht konfiguriert oder nicht erreichbar; falsche E-Mail-Adresse.',
'invalidAction' => 'Ungültige Aktion.',
'sendInvitation' => 'Einladung verschicken',
'invitationSuccessful' => "Einladung erfolgreich verschickt.",
'personalMessage' => 'Nachricht:',
'invitationSubject' => 'Einladung für %s',
'userinsystem' => "Nutzer ist im System bereits vorhanden.",
"areYouSure" => "Bist du sicher?",
"no" => "Nein",
"yes" => "Ja",
"VolumetricConversions" => "Umrechnung von Volumenangaben",
"Measurement" => "Maßeinheit",
"Value" => "Wert",
"Teaspoons" => "Teelöffel",
"Tablespoons" => "Esslöffel",
"FluidOunces" => "Flüssigkeits-Unze",
"Cups" => "Tassen",
"Pints" => "Pinten (ca. 0,5 Liter)",
"Quarts" => "Quart",
"Gallons" => "Gallonen",
"Liters" => "Liter",
"Serves" => "Portionen",
"ExportResults" => "Exportergebnisse",
"ExportImport" => "Export/Import",
"MassConversions" => "Umrechnung von Gewichtsangaben",
"cantDeleteYourself" => "Du kannst dich nicht selber löschen!",
"invitationsNotEnabled" => "Einladungen sind zur Zeit deaktiviert. <a href=\"http://rbook.sourceforge.net\">So kannst du Einladungen aktivieren</a> (nur Administratoren sehen diese Nachricht).",
"commaSeparated" => "(durch Kommata getrennt)",
"addPictureCaption" => "Beschreibung",
"addPicturePathToImage" => "Pfad zur Bilddatei",
"addPictureAddPicture" => "Bild hinzufügen",
"PrepTime" => "Vorbereitungszeit:",
"CookTime" => "Koch- bzw. Backzeit:",
"TotalTime" => "Gesamtzeit:",
"PrepTimeInMins" => "Vorbereitungszeit:<br/><span class=\"helptext\">(in Minuten)</span>",
"CookTimeInMins" => "Koch- bzw. Backzeit:<br/><span class=\"helptext\">(in Minuten)</span>",
"sortIngredientsHelp" => "Um die Reihenfolge zu verändern ziehe die Zutat per Drag-and-Drop an die neue Position.",
"sortStepsHelp" => "Um die Reihenfolge zu verändern ziehe den Schritt per Drag-and-Drop an die neue Position.",
"addPicture" => "Bild hinzufügen",
"deletePicture" => "Bild löschen",
"addPictureTo" => "Bild hinzufügen zu ",
"searchResults1" => "Die Suche ergab",
"searchResults2" => "Ergebnisse.",
"thumbnail" => "Vorschaubild",
"noThumbnail" => "kein Vorschaubild",
"noImage" => "noimage_de.gif",
"saveButton" => "save_de.gif",
"NewUser" => "Neuer Nutzer",
"DeleteSelected" => "Auswahl löschen",
"UProfile" => "Profil",
"searchGo" => "Los!",
"recipesBy" => "Rezepte von ",
"verifyEmail" => "E-Mail bestätigen:",
"ImpExpDisabled" => "Um Import und Export zu aktivieren definiere den IMPORTDIR-Parameter in der Datei config.php",
"submittedCat" => "Kategorie:",
"result_set_Results" => "Ergebnisse",
"submittedOn" => "Hinzugefügt am:",
"NewTitle" => "Neuer Titel",
"AddStep" => "Schritt hinzufügen",
"Add" => "Hinzufügen",
"Clear" => "Löschen",
"SlideTo" => "Benutze den Schiebregler, um<br/>die Zahl der Portionen anzupassen",
"GroceryList" => "Einkaufsliste",
"groceryList" => "Einkaufsliste",
"groceryListInstructions" => "Ziehe die Zutaten von der Zutatenliste hierher, um sie zur Einkaufsliste hinzuzu-<br />fügen.",
"groceryListViewInstructions" => "Verschiebe die Elemente, um sie zu sortieren. Lösche Elemente durch anclicken der Checkbox.",
"invalidImgType" => "Ungültiges Bildformat: Nur .gif und .jpg werden unterstützt.",
"notAdminExport" => "Nur Administratoren können die Exportdatei runterladen!",
"noImportDir" => "Import und Export sind noch nicht eingerichtet",
"noImportFile" => "Keine Importdatei angegeben",
"errorOpenImport" => "Konnte Datei nicht öffnen: ",
"passwordChanged" => "Passwort erfolgreich geändert.",
"numORecipes" => "Anzahl Rezepte:",
"numOCategories" => "Anzahl Kategorien:",
"notSpecified" => "nicht angegeben",
"AddComment" => "Kommentar hinzufügen",
"0stars" => "0 Sterne",
"1star" => "1 Stern",
"2stars" => "2 Sterne",
"3stars" => "3 Sterne",
"4stars" => "4 Sterne",
"5stars" => "5 Sterne",
"noRecipesHere" => "Leider keine Rezepte hier, möchtest du nicht welche <a href=\"addRecipe.php\">hinzufügen</a>?",
"Comments" => "Kommentare",
"Rating" => "Bewertung:",
"starsOutOfVotes" => "{0} Sterne aus {1} Bewertungen",
"votes" => "{0} Bewertungen",
"numOUsers" => "Anzahl Nutzer:",
"errSOT" => "'short_open_tag' ist in der php.ini auf 'Off' gesetzt",
"solSOT" => "Einige PHP-Skripte nutzen das 'short-hand tag'-Format. Es wird empfohlen, den Wert für 'short_open_tag' in der php.ini auf 'On' zu setzen",
"errFU" => "'file_uploads' (Dateien hochladen) ist in der php.ini auf 'Off' gesetzt",
"solFU" => "Es wird nicht möglich sein, Bilder hochzuladen. Setzte 'file_uploads' in der php.ini auf 'On', wenn du Bilder hochladen möchtest.",
"errMKDIR" => "Ein Testverzeichnis konnte nicht erstellt werden",
"solMKDIR" => "Wahrscheinlich hat der Webserver-Prozess keine Schreibrechte. Obwohl die Rezepte in einer Datenbank gespeichert sind, werden die Bilder in einem Unterverzeichnis des Installationsordners abgelegt. Bitte lege das Verzeichnis 'img' manuell an und stelle sicher, dass der Server-Prozess Schreibrechte für dies Verzeichnis hat.",
"errWriteFile" => "Eine Testdatei konnte nicht geschrieben werden",
"solWriteFile" => "Wahrscheinlich hat der Webserver-Prozess keine Schreibrechte. Du wirst keine Bilder benutzen können. Außerdem musst du die Datei config.php manuell anlegen (weitere Anweisungen folgen nach der Installation).",
"configurationScan" => "Prüfen der Systemvorraussetzungen",
"issuesConfiguration" => "Das Installationsprogramm hat deine Konfiguration untersucht und einige Probleme gefunden, die eventuell die Ausführung von rbook stören könnten.",
"Solution" => "Lösung",
"Warning" => "Warnung",
"Error" => "Fehler",
"rerunScan" => "Erneut überprüfen",
"proceedInstallation" => "Weiter zur Installation",
"Installation" => "Installation",
"DatabaseHost" => "Datenbankserver (IP-Adresse)",
"DatabaseName" => "Datenbankname",
"AdminUser" => "DB-Admin",
"installDesc1" => "Das Installationsprogramm erstellt das Datenbankschema und erstellt dann eine Datei <em>config.php</em>, die alle diese Einstellungen enthält.",
"installDesc2" => "Um die Einstellungen nach der Installation zu verändern, bitte entweder die Installation erneut ausführen oder die Änderungen direkt in der Datei config.php eintragen.",
"DatabaseInformation" => "Datenbankinformationen",
"DatabaseInstallDesc" => "Während der Datenbankinstallation nutzt das Installationsprogramm das Benutzerkonto des <em>DB-Admin</em>, um das Datenbankschema und die anfängliche Ausprägung der Tabellen zu erstellen. Dies ist bei MySQL in den meisten Fällen der Nutzer 'root'.<br />Wenn rbook installiert ist, wird zur Kommunikation mit der Datenbank das Benutzerkonto genommen, das im Feld <em>Datenbankbenutzer</em> angegeben ist. Wenn hier kein Benutzer angegeben wurde, wird weiterhin das Benutzerkonto des <em>DB-Admin</em> benutzt, um auf die Datenbank zuzugreifen (nicht empfohlen).<br />Wenn der angegebene Datenbanknutzer bei der Installation nicht existiert, wird er vom Installationsprogramm erstellt.",
"createDatabase" => "Datenbank erstellen",
"DatabaseUserName" => "Datenbankbenutzer",
"BasicConfiguration" => "Grundkonfiguration",
"ApplicationTitle" => "Name der Rezeptsammlung",
"BaseURI" => "Basis URI",
"Skin" => "Skin",
"SkinDesc" => "Ein 'skin' definiert das 'look and feel' der Anwendung, also das Aussehen und die Oberfläche. Zur Zeit werden zwei Skins mit rbook mitgeliefert. Der Skin <em>default</em> iste die Standardoberfläche mit einer zentrierten Seitenanzeige, ergänzt durch Spalten an den Seiten. Der Skin <em>liquid</em> ist etwas freier konfigurierbar und kommt ohne Seitenspalten (dieser Skin ist mehr ein Beispiel, wie rbook erweitert werden kann).",
"InitialAdminUser" => "Anfängliches Administratorkonto",
"InitialAdminUserDesc" => "Das Installationsprogramm erstellt ein Administratorkonto für rbook (die Webseite). Der Benutzername für dieses Konto ist 'root' und das Passwort ist 'password'.",
"ViewPolicy" => "Zugriffsrechte",
"ViewPolicyDesc" => "Entweder kannst du deine Rezepte für JEDEN freigeben, oder aber nur für registrierte Mitglieder. Setze diese Einstellung auf 'Nur Mitglieder', wenn Besucher der Seite sich einloggen sollen, bevor sie Rezepte ansehen dürfen.",
"MembersOnly" => "Nur Mitglieder",
"Everyone" => "Jeder",
"ExportImportDesc" => "<em>(Optional)</em> Gib hier ein Verzeichnis an, in das rbook Daten exportieren kann. Dies sollte ein Verzeichnis sein, für das dein Webserver Schreibrechte hat (du kannst dieses Verzeichnis jederzeit manuell anlegen). Du kannst dieses Feld auch zunächst freilassen und den Parameter 'IMPORTDIR' in der config.php nach der Installation ändern. Wenn hier ein Verzeichnis angegeben wird, hat der Admin Nutzer zwei weitere Menüpunkte 'Importieren' und 'Exportieren', die das Importieren bzw. Exportieren von Dateien aus und in dieses Verzeichnis ermöglichen.",
"ExportDirectory" => "Exportverzeichnis",
"InvitationsDesc" => "<em>(Optional)</em> Bestehende Nutzer können neuen Nutzern Einladungen schicken und ihnen so die Möglichkeit geben, selber ein registriertes Mitglied zu werden. Jeder bestehende Nutzer hat eine maximale Anzahl Einladungen zur Verfügung. Wenn die hier angegebene Nummer größer 0 ist, werden Einladungen aktiviert.",
"MaxInvitations" => "Maximale Einladungen pro Nutzer",
"Images" => "Bilder",
"ImagesDesc" => "Es ist möglich, mehrere Bilder für ein Rezept zu speichern. Die Bearbeitung der Bilder (z.B. Verkleinern), wird vom Programm 'ImageMagick' durchgeführt, welches installiert sein muss, um dieses Feature zu nutzen. Gib hier den Pfad zum <em>convert</em>-Programm an. Z.B. unter Windows, <code>c:\progra~1\imagemagick\convert.exe</code>.",
"ImageMagickPath" => "Pfad zum Programm 'ImageMagick'",
"InstallationComplete" => "Installation Abgeschlossen",
"configWriteError" => "Das Installationsprogramm konnte die Datei 'config.php' nicht erstellen. Bitte erstelle diese Datei manuell im rbook Grundverzeichnis und füge die folgenden Daten dort ein.",
"verifyInstallation" => "Überprüfe die Installation durch Aufrufen der rbook Hauptseite. Wenn keine Fehlermeldungen erscheinen, kann rbook sich zur Datenbank verbinden und die Installation war erfolgreich.",
"templatesWriteable" => "Überprüfe, ob der Webserver-Prozess für das Verzeichnis 'templates_c' Schreibrechte hat.",
"removeInstallDir1" => "Lösche das Verzeichnis 'install'!",
"removeInstallDir2" => "Dies verhindert eine weitere Installation durch Unbefugte.",
"AccessSite" => "Weiter zur rbook Hauptseite",
"hrs" => "Std",
"min" => "Min",
"AnErrorHasOccurred" => "Ein Fehler ist aufgetreten",
"ErrorNumber" => "Fehlernummer",
"ErrorMessage" => "Fehlernachricht",
"ErrorFile" => "Quelldatei",
"ErrorLine" => "Zeile",
"errPearDbNotFound" => "<a href='http://pear.php.net/DB'>PEAR DB</a>, eine benötigte Komponente, konnte nicht gefunden werden.",
"pearDbNotFound" => "Es gibt zwei Lösungen für dies Problem: <ol><li>Installiere PEAR DB über die Kommandozeile mit dem Befehl '<code>pear install db</code>' (der aktuelle Nutzer braucht natürlich genügend Rechte auf dem System)</li><li>füge das Unterverzeichnis 'extlib/DB-1.7.6' zur Variable 'include_paths' in deiner php.ini hinzu. Starte dann den Webserver neu, damit die geänderte Konfiguration wirksam wird.</li></ol>",
"pleaseEnterCaptcha" => "Bitte gib die Buchstaben aus dem oben gezeigten Bild ein und schicke dies Formular ab.",
"submitChallenge" => "Sicherheitsabfrage abschicken",
"captcha" => "Sicherheitsabfrage",
"invalidCaptchaResponse" => "Ungültige Antwort. Bitte noch einmal probieren.",
"registrationComplete" => "Registrierung fertiggestellt",
"registrationCompleteP" => "Eine E-Mail wurde an die angegebene Adresse verschickt. Bitte folge den Anweisungen in dieser Mail um die Registrierung abzuschließen. Danke.",
"newUser" => "Neuer Nutzer?",
"register" => "Registrierung eines neuen Nutzers",
"Register" => "Registrieren",
"exportTheRepository" => "Datenbestand exportieren",
"prev" => "zurück",
"next" => "vor",
"Cat01" => "Auflauf",
"Cat02" => "Dessert",
"Cat03" => "Getränke",
"Cat04" => "Hauptgericht",
"Cat05" => "Pasta",
"Cat06" => "Geflügel",
"Cat07" => "Salat",
"Cat08" => "Fisch",
"Cat09" => "Suppe",
"Cat10" => "Gemüse",
"guestbook" => "Gästebuch",
"plsEnterComment" => "Bitte gib einen Kommentar ein!",
"plsEnterName" => "Bitte einen Namen eingeben!",
"comment" => "Kommentar",
"sorry" => "Entschuldigung...",
"noresults" => "Deine Suche lieferte keine Ergebnisse. Bitte probiere einen anderen Suchbegriff.",
"help" => "Hilfe",
"helptext1" => "rbook (kurz für 'recipe book', also 'Rezeptbuch') ist ein System zur Verwaltung von Rezepten. Neben der Anzeige von vorhandenen Rezepten können auch neue Rezepte hinzugefügt (und später bearbeitet) werden, um die Sammlung zu erweitern. Eine tolle Möglichkeit, die eigene Rezeptsammlung zu verwalten und Rezepte mit Familie und Freunden auszutauschen. Der Zugang zu dieser Seite ist eventuell eingeschränkt. Bitte wende dich an den Seitenbetreiber, um einen Zugang zu erhalten. Alle Passwörter werden verschlüsselt gespeichert.",
"helptext2" => "Auf der Startseite werden die neuesten Rezepte präsentiert. Es ist auch möglich, hier die beliebtesten Rezepte der Sammlung anzuzeigen. Auf der linken Seite des Bildschirms befinden sich Kategorien (z.B. Salat oder Dessert), in welche die Rezepte eingeteilt sind. Suchen nach Titeln oder Zutaten ist im rechten oberen Bereich der Seite möglich. Registrierte Benutzer können sich ihre Lieblingsrezepte in einem eigenen Kochbuch ('meine Rezepte') zusammenstellen.",
"helptext3" => "Das Eingeben neuer Rezepte ist registrierten Benutzern vorbehalten. Neben allgemeinen Informationen zu einem Rezept (Name, Quelle, Zubereitungszeit etc.) werden die Zutaten (evtl. organisiert in Zutatensätze) und die Arbeitsschritte eingegeben. Auch das Hinzufügen von Fotos ist möglich. Wenn zu einem Rezept mehrere Bilder vorhanden sind, wird eine Diashow von diesen erstellt.",
"helptext4" => "Für weitere Informationen besuche bitte die rbook-Homepage im Internet oder wende dich an den Seitenbetreiber. Es wäre auch nett, wenn du ein paar Worte im Gästebuch dieser Seite hinterlässt. Danke :-)",
"helptext5" => "Für Benutzer von Mozilla Firefox: rbook kann als Such-Plugin in Firefox integriert werden. Damit ist es möglich, jederzeit über den Browser auf der Seite nach Rezepten zu suchen. Eine bequeme und schnelle Zugriffsmöglichkeit.",
"installplugin" => "Plugin jetzt installieren",
"antispam" => "Anti-Spam",
"antispamwrong" => "Bitte auch das Anti-Spam-Feld korrekt ausfüllen!",
"BasicConfigurationDesc" => "Hier kannst du einen Titel für deine Seite wählen. Außerdem wird das Wurzelverzeichnis deiner rbook-Installation auf dem Webserver benötigt. Angenommen, du greifst auf diese Seite hier über die URL 'http://deinserver/meinordner/rezepte/' zu, dann trage bitte '/meinordner/rezepte/' als Basis URI ein.",
"deletePictures" => "Bilder löschen",
"backToRecipe" => "Zurück zum Rezept",
"deleteThisImage" => "Dieses Bild löschen",
"allRecipes" => "Alle Rezepte",
"randomRecipe" => "Zufälliges Rezept",
"missingTitle" => "Bitte einen Titel eingeben!",
"missingCategory" => "Bitte mindestens eine Kategorie wählen!",
"missingIngredients" => "Bitte mindestens einen Zutatensatz eingeben!",
"missingSteps" => "Bitte mindestens einen Arbeitsschritt eingeben!"
);
?>