<?php
/*
 * rbook Recipe Management System
 * Copyright (C) 2005 Andrew Violette andrew@andrewviolette.net
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

/**
 * Resource bundle for English language.
 *
 * @author Andrew Violette
 * @since 0.9
 * @version $Id: resources_en.php,v 1.19 2007/04/06 11:03:31 aviolette Exp $
 */

$i18n_messages_en = 
array(
'accountDisabled' => 'This account is disabled.',
"active" => "active",
'addUser' => 'Add User',
"Bookmark" => "Bookmark",
"Created" => "Created",
"delete" => "delete",
"DeleteQuestion" => "Delete?",
"DiscardAndView" => "Cancel",
"disabled" => "disabled",
'editCategories' => "Edit Categories",
'editUser' => 'Edit User',
'EditGroceryList' => 'Edit',
"File" => "File",
"SortBy" => "Sort by: {0} / {1}",
"popular" => "popular",
"recent" => "recent",
"ProfileHeader" => "Profile: {0}",
"SeeAll" => "See all {0} recipes by {1}",
"Favorite" => "Favorite Food",
"Website" => "Website",
"deleteIngredientSetTooltip" => "Deletes the entire ingredient set",
"MostRecentRecipesBy" => "Most Recent Recipes by {0}",
"MemberSince" => "Member since: {0}",
'importTitle' => "Import",
"importWarning" => "Warning!!! importing an import file blows away the repository and replaces the users, categories, and recipes defined in the import file.",
"initialPassword" => "User's initial password will be <em>password</em>.",
"invited" => "invited",
"newCategory" => "New Category",
"noImportFiles" => "There are no import files in the drop zone.",
'noRecipeSelected' => "No recipe selected.",
'Profile' => 'Profile',
"resetPassword" => "Reset Password",
"resetPasswordDesc" => "Change user password back to <em>password</em>:",
"SaveAndView" => "Save and View",
"saveToDelicious" => "Save to del.icio.us",
"saveToGoogleBookmarks" => "Save to google",
"selectFileToImport" => "Select a file to import:",
"userCannotBeDeleted" => "Some users could not be deleted; probably because they own recipes.  Either delete the recipes the users own or disable their accounts instead.",
'userOrPasswordIncorrect' => 'The user name or password is incorrect.',
'VerifyInvitation' => 'Verify Invitation',
"categoryName" => "Name",
"categoryNew" => "New",
"Delete" => "Delete",
"Go" => "Go",
'remove' => 'remove',
"TitleSearch" => "Title search",
"newRecipe" => "new recipe",
'MyRecipes' => 'My Recipes',
"myRecipes" => "my recipes",
"conversion" => "conversion",
"exportMsg" => "Specify a file name for the export file.  This will be placed in the directory specified in the configuration file.",
"Type" => "Type",
"Status" => "Status",
"admin" => "admin",
"readonly" => "readonly",
"normal" => "normal",
"home" => "home",
"Step" => "Step",
"OldPassword" => "Old password",
"NewPassword" => "New password",
"ConfirmNewPassword" => "Confirm new password",
"Ingredients" => "Ingredients",
"Amount" => "Amount",
"Description" => "Description",
"upButton" => "up",
"downButton" => "down",
"AddIngredient" => "add",
"Conversions" => "Conversions",
"Grams" => "Grams",
"Milligrams" => "Milligrams",
"Ounces" => "Ounces",
"Pounds" => "Pounds",
"IngredientSets" => "Ingredient Sets",
"AddIngredientSet" => "Add ingredient set",
"PickReplacementCategory" => "Pick Replacement Category",
"replacementMsg" => "There are existing recipes in the categories that you have selected for deletion.  Select a category from the list below that will replace the categories you are deleting.",
'User' => 'User',
'Steps' => 'Steps',
'Note' => 'Note',
'Notes' => 'Notes',
'ExportFile' => "Export file:",
'submittedBy' => 'Submitted by:',
'rightsLevel' => 'Rights Level',
'recipecount' => 'Recipes',
'logout' => 'logout',
'Login' => 'Login',
'UserName' => 'User name',
'Email' => 'Email',
'Name' => 'Name',
'Submit' => 'Submit',
'Password' => 'Password',
'rememberme' => 'Remember me',
'invite' => 'invite',
'Invite' => 'Invite',
'Invitations' => 'Invitations',
'remainingInvitations' => 'Remaining invitations',
'Admin' => 'Admin',
'Users' => 'Users',
'Import' => 'Import',
'Export' => 'Export',
'Categories' => 'Categories',
'About' => 'About',
'deleteRecipe' => 'Delete',
'printRecipe' => 'Print',
'Information' => 'Information',
'Source' => 'Source',
'Preheat' => 'Preheat',
'Title' => 'Title',
'Category' => 'Category',
'Readonly' => 'Readonly',
'Normal' => 'Normal',
'Admin' => 'Admin',
'Passwords' => 'Passwords',
'Save' => 'Save',
'Cancel' => 'Cancel',
'Continue' => 'Continue',
'disabled' => 'disabled',
'addToMyRecipes' => 'Add to My Recipes',
'editRecipe' => 'Edit',
'leaveBlank' => 'Leave these fields blank if you do not want to change your password.',
'readonlyDesc' => 'Can search, browse and view reciepes',
'normalDesc' => 'Can search, browse, view and edit recipes that were created by themselves.  Can invite others to be members.',
'adminDesc' => 'Can search, browse, view, and edit all recipes.  Can create and edit users and categories.',
'noActiveRecipe' => 'No active recipe.',
'invalidInvitation' => 'Invalid invitation code',
'invitationUsed' => 'Invitation has already been used',
'emailDoesNotMatch' => 'Email does not match the invitation.',
'mostRecentAdditions' => 'Most Recent Additions',
'errorRetrievingUser' => 'Error retrieving user: %s',
'noExportFileSpecified' => "No export file specified.",
'exportSuccessful' => 'Export successful!',
'forgotPassword' => 'Forgot Password',
'noPermissionToEditRecipe' => "You do not have permission to edit this recipe.",
'noPermissionToDeleteRecipe' => 'You do not have permission to delete that recipe.',
'activationLinkSent' => 'An email has been sent to your account with a link that can reactivate your account.',
'recoverPassword' => 'Recover Password',
'emailToRecover' => 'Please enter the email address that was used to create the account.  An email will be sent to this address with further instructions.',
'userNotInSystem' => 'User not in system.',
'emailUnsuccessful' => 'There was a problems sending the email.  Possible causes include: the mail server being down, mail being configured improperly on your host, or an incorrect email address.',
'invalidAction' => 'Invalid action.',
'sendInvitation' => 'Send Invitation',
'invitationSuccessful' => "Invitation sent successfully.",
'personalMessage' => 'Message:',
'invitationSubject' => 'Invitation to %s',
'userinsystem' => "User already in system.",
"areYouSure" => "are you sure?",
"no" => "no",
"yes" => "yes",
"VolumetricConversions" => "Volumetric Conversions",
"Measurement" => "Measurement",
"Value" => "Value",
"Teaspoons" => "Teaspoons",
"Tablespoons" => "Tablespoons",
"FluidOunces" => "Fluid ounces",
"Cups" => "Cups",
"Pints" => "Pints",
"Quarts" => "Quarts",
"Gallons" => "Gallons",
"Liters" => "Liters",
"Serves" => "Serves",
"ExportResults" => "Export Results",
"ExportImport" => "Export/Import",
"MassConversions" => "Mass Conversions",
"cantDeleteYourself" => "You can't delete yourself!",
"invitationsNotEnabled" => "Invitations are not enabled.  Click  <a href=\"http://rbook.sourceforge.net\">here</a> for instructions to enable invitations. (only site admins see this message)",
"commaSeparated" => "(comma-separated)",
"addPictureCaption" => "Caption",
"addPicturePathToImage" => "Path to image",
"addPictureAddPicture" => "Add Picture",
"PrepTime" => "Prep time:",
"CookTime" => "Cook time:",
"TotalTime" => "Total time:",
"PrepTimeInMins" => "Prep Time:<br/><span class=\"helptext\">(in minutes)</span>",
"CookTimeInMins" => "Cook Time:<br/><span class=\"helptext\">(in minutes)</span>",
"sortIngredientsHelp" => "To change the positioning, select anywhere except the input box, then drag-and-drop the ingredient to a new position.",
"sortStepsHelp" => "To change the positioning, select anywhere except the input box, then drag-and-drop the step to a new position.",
"addPicture" => "Add Picture",
"deletePicture" => "Delete Picture",
"addPictureTo" => "Add a picture to ",
"searchResults1" => "There were",
"searchResults2" => "results.",
"thumbnail" => "thumbnail",
"noThumbnail" => "no thumbnail",
"noImage" => "noimage_en.gif",
"saveButton" => "save_en.gif",
"NewUser" => "New User",
"DeleteSelected" => "Delete Selected",
"UProfile" => "Profile",
"searchGo" => "Go",
"recipesBy" => "Recipes by ",
"verifyEmail" => "Verify Email:",
"ImpExpDisabled" => "To enable import/export, define the IMPORTDIR parameter in config.php",
"submittedCat" => "Category:",
"result_set_Results" => "Results",
"submittedOn" => "Submitted on:",
"NewTitle" => "New Title",
"AddStep" => "Add step",
"Add" => "Add",
"Clear" => "Clear",
"SlideTo" => "Use the slider to adjust the recipe <br/>to the correct number of servings",
"GroceryList" => "Grocery List",
"groceryList" => "grocery list",
"groceryListInstructions" => "Drag items from the ingredients list here to add them to the list. Click on the items to edit them.",
"groceryListViewInstructions" => "Drag items to sort them.  Delete items by checking the check box.",
"invalidImgType" => "Invalid image type: Only gif and jpg are supported currently.",
"notAdminExport" => "You must be an admin user to download an export!",
"noImportDir" => "You are not setup for export and import",
"noImportFile" => "No import file specified",
"errorOpenImport" => "Couldn't open file: ",
"passwordChanged" => "Password changed successfully.",
"numORecipes" => "Number of recipes:",
"numOCategories" => "Number of categories:",
"notSpecified" => "unspecified",
"AddComment" => "Add a comment",
"0stars" => "0 stars",
"1star" => "1 star",
"2stars" => "2 stars",
"3stars" => "3 stars",
"4stars" => "4 stars",
"5stars" => "5 stars",
"noRecipesHere" => "There are no recipes here, why don't you <a href=\"addRecipe.php\">add some</a>?",
"Comments" => "Comments",
"Rating" => "Rating:",
"starsOutOfVotes" => "{0} stars out of {1} votes",
"votes" => "{0} votes",
"numOUsers" => "Number of users:",
"errSOT" => "short_open_tag is set to Off in php.ini",
"solSOT" => "Some PHP files use the short-hand tag format. It is suggested that you set short_open_tag in your php.ini to 'On'",
"errFU" => "file_uploads is set to Off in your php.ini",
"solFU" => "You will not be able to upload images. Turn this in the PHP.ini if you wish to upload recipe images.",
"errMKDIR" => "Unable to create a test directory",
"solMKDIR" => "This is probably because your webserver process doesn't have write permissions. Although the recipes are stored in a database, the images are stored on the subdirectory of the installation.  You will manually have to create the 'img' directory and make sure that it is writable by the server process.",
"errWriteFile" => "Unable to write a test file",
"solWriteFile" => "This is probably because your webserver process doesn't have write permissions. This will prevent you from using images and you will have to manually create the config.php file after installation (instructions will be shown after installation).",
"configurationScan" => "Configuration Scan",
"issuesConfiguration" => "The installation program has scanned your configuration and found some issues that may or may not cause issues with the execution of this program.",
"Solution" => "Solution",
"Warning" => "Warning",
"Error" => "Error",
"rerunScan" => "Re-run scan",
"proceedInstallation" => "Proceed to installation",
"Installation" => "Installation",
"DatabaseHost" => "Database Host",
"DatabaseName" => "Database Name",
"AdminUser" => "Admin User",
"installDesc1" => "The installation program builds the database schema and then builds a PHP file called <em>config.php</em>, which contains all these configuration parameters.",
"installDesc2" => "To change these parameters after the installation has been run, either re-run the installation, or modify config.php.",
"DatabaseInformation" => "Database Information",
"DatabaseInstallDesc" => "During the database installation, the installation program uses the <em>Admin User</em> to build out the database schema and do the initial table population. Once the application is installed, the user specified in the <em>Database user name</em> field is used to talk to the database. If this user is not specified, the admin user is used to access the database (not recommended). If the database user does not exist, it will be created by the installation.",
"createDatabase" => "create database",
"DatabaseUserName" => "Database user name",
"BasicConfiguration" => "Basic Configuration",
"ApplicationTitle" => "Application title",
"BaseURI" => "Base URI",
"Skin" => "Skin",
"SkinDesc" => "The 'skin' defines the look and feel.  There are currently two skins that come with 'rBook'. The <em>default</em> skin is a elastic view that is centered on the page with left side bars. The <em>liquid</em> view provides no sidebars and the width can be changed (this is not as fully functional as the <em>default</em> view but is mainly meant for pedagogical purposes on how to extend rbook.)",
"InitialAdminUser" => "Initial Admin User",
"InitialAdminUserDesc" => "The setup program creates one admin user after the database has been initialized. The initial username of this user will be 'root' and the password will be 'password'.",
"ViewPolicy" => "View Policy",
"ViewPolicyDesc" => "Everyone can view the recipes or just members. Set this to 'Members only' if you want people to log on before they are able to view the recipes.",
"MembersOnly" => "Members only",
"Everyone" => "Everyone",
"ExportImportDesc" => "<em>(Optional)</em> Specify a directory on your server where rBook can export its data.  This should be a directory that is writable by your webserver (you can create this directory manually at anytime). You can leave this blank and modify the IMPORTDIR field in config.php after installation.  If this field is specified, the admin user will have two additional menu items: Export and Import, which will allow them to export and import files from this directory.",
"ExportDirectory" => "Export directory",
"InvitationsDesc" => "<em>(Optional)</em> You can allow users to invite other users to become members. Each user will have a maximum number of users that they can invite. If the number here is greater than 0, invitations will be enabled.",
"MaxInvitations" => "Maximum invitations per user",
"Images" => "Images",
"ImagesDesc" => "rBook allows you to store multiple images for a recipe. Image manipulation is performed by ImageMagick, which must be present in order to use this feature. Specify the path to the <em>convert</em> program including the program name. For example, <code>c:\progra~1\imagemagick\convert.exe</code> on Windows.",
"ImageMagickPath" => "ImageMagick convert path",
"InstallationComplete" => "Installation Complete",
"configWriteError" => "The installation program was unable to create the config.php file. Please create the config.php file in the top-level directory by pasting the data below.",
"verifyInstallation" => "Verify the installation by going to the application URL and verifying that it installed correctly. If it displays without errors then it is able to connect to the database.",
"templatesWriteable" => "Make sure the skins/<i>skin</i>/templates_c directory exists and is writable by the web-server process.  If not create it and make it writeable by your webserver process",
"removeInstallDir1" => "Remove the install directory!",
"removeInstallDir2" => "This will prevent others from running the installation.",
"AccessSite" => "Access the site",
"hrs" => "hrs",
"min" => "min",
"AnErrorHasOccurred" => "An error has occurred",
"ErrorNumber" => "Error number",
"ErrorMessage" => "Error mesage",
"ErrorFile" => "Source file",
"ErrorLine" => "Line",
"errPearDbNotFound" => "<a href='http://pear.php.net/DB'>PEAR DB</a>, which is a required component is not found.",
"pearDbNotFound" => "There are two solutions:  <ol><li>Install PEAR DB by running the command '<code>pear install db</code>' from the command line (with a user with appropriate permissions)</li><li>append the extlib/DB-1.7.6 subdirectory of this installation to your php.ini include_paths variable. Restart your apache server to pickup the configuration changes</li></ol>",
"pleaseEnterCaptcha" => "Please enter the letters that appear in the image above and submit the form.",
"submitChallenge" => "Submit Challenge",
"captcha" => "Security challenge",
"invalidCaptchaResponse" => "Invalid response.  Try again.",
"registrationComplete" => "Registration Complete",
"registrationCompleteP" => "An email was sent to the address provided.  Please follow the instructions in the email to complete the registration.  Thanks.",
"newUser" => "New User?",
"register" => "New User Registration",
"Register" => "Register",
"exportTheRepository" => "Export the Repository",
"prev" => "prev",
"next" => "next",
"Cat01" => "Barbecue",
"Cat02" => "Desserts",
"Cat03" => "Drinks",
"Cat04" => "Main",
"Cat05" => "Pasta",
"Cat06" => "Poultry",
"Cat07" => "Salads",
"Cat08" => "Seafood",
"Cat09" => "Soups",
"Cat10" => "Vegetables",
"guestbook" => "Guestbook",
"plsEnterComment" => "Please enter a comment!",
"plsEnterName" => "Please enter a name!",
"comment" => "Comment",
"sorry" => "Sorry...",
"noresults" => "Your search returned no results. Please try a different search term.",
"help" => "Help",
"helptext1" => "rbook (short for 'recipe book') is a recipe management system. Besides viewing existing recipes you can add (and later edit) your own recipes to expand the collection. A great way to organize your own recipes and share them with your family and friends. Access to the site might be restricted. Please contact the site owner for read and/or write access. All passwords are saved to the database in encrypted form.",
"helptext2" => "Beginning on the homepage you'll see the most recent recipes. You can also switch this view to the most popular ones. Recipes can also be sorted into categories, which you can see on the left side of the screen. Searching for recipes is possible in the topbar. Registered users can also save their favourite recipes to a personal cookbook ('my recipes').",
"helptext3" => "Adding new recipes is only possible for registered users. You can add general information (name, source, preheat values, preparation time, ...), ingredients (even organized with ingredient sets), steps and additional notes. Adding images is also possible. When adding more than one picture to a recipe, a nice slideshow will be created.",
"helptext4" => "For further informations please visit rbook on the web or contact the site owner. Also feel free to leave some nice words in this site's guestbook.",
"helptext5" => "Mozilla Firefox users: rbook offers a search plugin for Firefox. Once installed, you can search for recipes from within the browser and you'll be directly forwarded to the result page.",
"installplugin" => "Click here to install the plugin.",
"antispam" => "Spam protection",
"antispamwrong" => "Please also fill in the spam protection field!",
"BasicConfigurationDesc" => "Please chose a title for your page. You also need to enter the root directory of your rbook installation here. For example let's say you are viewing this page with the URL 'http://yourserver/yourfolder/recipes/', please set '/yourfolder/recipes/' as your base URI.",
"deletePictures" => "Delete pictures",
"backToRecipe" => "Return to recipe",
"deleteThisImage" => "Delete this image",
"allRecipes" => "All recipes",
"randomRecipe" => "Random recipe",
"missingTitle" => "Please enter a title for this recipe!",
"missingCategory" => "Please chose at least one category for this recipe!",
"missingIngredients" => "Please enter at least one ingredient set for this recipe!",
"missingSteps" => "Please enter at least one step for this recipe!"
);
?>